server:
  port: 8002
mybatis:
  type-aliases-package: com.demo.springcloud.api.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: provider-dept-800x
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept8002

info:
  app.name: qiuche-springcloud
  company.name: blog.qiuchestudy.com
